sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8.9.4'
before_install:
  - npm i -g npm@^5.6.0
before_script:
  - npm prune
after_success:
  - npm run semantic-release
branches:
  only:
    - master
